apiVersion: v1
kind: Service
metadata:
  name: {{ template "explorerdb.fullname" . }}
  labels:
    app: {{ template "explorerdb.name" . }}
    chart: {{ template "explorerdb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "explorerdb.name" . }}
    release: {{ .Release.Name }}
  clusterIP: None
  ports:
  - name: http
    port: 5432
    protocol: TCP
